### ISSUE TITLE
Example for intregrating this library in Elixir

### ISSUE THREAD

**Issue by LeeWong** [skulup/pulserl#1]
Hi,

Could you please create an example on how to use this library with Elixir? I am having troubles to integrate this library.

**Comment by alphashaw** [comment]
Sorry for reaching late. We're are also using this in Elixir environment. Unfortunately, we haven't package it to Hex this means, you have to fetch the dependency from github as below: 

In add the dependency to your `mix.exs`
```
defp deps do
 [
  ...,
   {:pulserl, git: "https://github.com/skulup/pulserl.git", branch: "master"}
 ]
```
In your Elixir project's home directory, fetch the dependency with: 
`mix deps.get`
After that, run `iex -S mix` to start the project and play with Elixir's shell

We're trying to make pulserl to have an easy integration with Elixir, so most functions in it that accept **string[erlang]** also accepts **binary[erlang]** which is Elixir's equivalent of **string**.

So the following is the **Elixir's** equivalent of the `README.md` Erlang examples.

```
  # A demo function to log the value of consumed messages that will be produced blow.
  :pulserl.start_consumption_in_background("test-topic")

  # Asycnhrounous produce
  promise = :pulserl.produce("test-topic", "Asycn produce message")
  :pulserl.await(promise)   # messageId() as below

  # Asycnhrounous produce. Response notification is via callback (fun/1)
  :pulserl.produce("test-topic", "Hello", fn(res) -> IO.put("Response: #{inspect(res)}") end)

  # Synchronous produce
  :pulserl.sync_produce("test-topic", "Sync produce message")  # messageId() as below

```

To use pulserl's records in Elixir, take a look at: [Defining Erlang's record in Elixir](https://hexdocs.pm/elixir/Record.html#defrecord/3).

As sample for the Erlang's `messageId` record definition in Elixir:
```
 defmodule Pulserl.Producer.MessageId do

  require Record
  Record.defrecord(:messageId, Record.extract(:messageId, from_lib: "pulserl/include/pulserl.hrl")) 
  
end
```
This record can be used with the syntax `messageId()` after importing the module: `Pulserl.Producer.MessageId`

For easier integration, we're looking at the option of having an Elixir wrapper (separate project) over `Pulserl` where we expose all Erlang records to Struct(better way for Elixir) and other data types as well.
