### ISSUE TITLE
Next features?

### ISSUE THREAD

**Issue by sabudaye** [skulup/pulserl#7]
Hi, @alphashaw
You asked me to share my thoughts about the next features in pulserl. I think the most missing feature is authentication and maybe a bit more testing (like test if TLS is actually working), how do you think?

Btw, we are trying to implement a test for batched messages and found something weird:
https://github.com/skulup/pulserl/blob/master/src/pulserl_utils.erl#L39
It is always false, right? So batch in messageId structure is always undefined, no matter if batches are actually used.
Could you please clarify it a bit?

**Comment by alphashaw** [comment]
Hello @sabudaye ,
I agreed for authentication. 

**Issue with batching**

In Apache Pulsar, batch messages are stored and delivered as the batch not individually. In other words, messages are understood to be batched from the consumer end only if they were batched by the producer in the first place. See in the consumer code where it's used: [https://github.com/skulup/pulserl/blob/master/src/pulserl_consumer.erl#L393](https://github.com/skulup/pulserl/blob/master/src/pulserl_consumer.erl#L393) - when the metadata of the decoded command says the messages are in batch,  [https://github.com/skulup/pulserl/blob/master/src/pulserl_consumer.erl#L382](https://github.com/skulup/pulserl/blob/master/src/pulserl_consumer.erl#L382). I wrote a simple check with 10 messages published to a non-partitioned count topic and using the async API (to increases the chances of them being batched before `batch_max_delay_ms, 10ms` timedout); I observed the following consumed messages from the consumer.

![batch](https://user-images.githubusercontent.com/14175735/91840037-8fed2680-ec3f-11ea-840c-0e6f49efd5b0.png)

 I've also added a test for this in the consumer test suit: [https://github.com/skulup/pulserl/blob/master/test/consumer_SUITE.erl#L51](https://github.com/skulup/pulserl/blob/master/test/consumer_SUITE.erl#L51)

**Issue with TLS**
I've TLS working well in my environment. I have added sample localhost [certificates](https://github.com/skulup/pulserl/tree/master/config/certs) and configured [docker-compose.yaml](https://github.com/skulup/pulserl/blob/master/docker-compose.yml) to open Pulsar's TLS port. I have also configured the test build to start the client in TLS mode.

**Comment by sabudaye** [comment]
Thanks, looks great!
