### ISSUE TITLE
Example in ReadMe failed

### ISSUE THREAD

**Issue by yangou** [skulup/pulserl#8]
This producer example failed

```erlang
pulserl:produce("test-topic", "Hello", fun(Res) -> io:format("Response: ~p~n", [Res]) end).
```

```** exception error: no function clause matching pulserl:produce("test-topic","Hello",#Fun<erl_eval.7.126501267>) (/Users/yang/Workspace/blueshift/pulserl/src/pulserl.erl, line 91)```

Potential fix: (I'm not sure why changing it to `orelse` fixes it.)

Change:
https://github.com/skulup/pulserl/blob/9b491a0e8247d68545dea274a63268dbb2c3afdd/src/pulserl.erl#L93

to
```erlang
(is_function(Callback) orelse Callback == ?UNDEF) -> 
```

**Comment by alphashaw** [comment]
Fixed in the following [PR](https://github.com/skulup/pulserl/pull/9)
